project:
  type: book

book:
  title: "*Statistical rethinking* 2 with rstan and the tidyverse"
  subtitle: "version 0.5.0"
  author: "A. Solomon Kurz"
  date: now
  favicon: mischa_favicon.png
  search: true
  repo-url: https://github.com/ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed
  repo-actions: issue
  chapters:
    - index.qmd
    - 01.qmd
    - 02.qmd
    - 03.qmd
    - 04.qmd
    - 05.qmd
    - 06.qmd
    - 07.qmd
    - 08.qmd
    - 09.qmd
    - 10.qmd
    - 11.qmd
    - 12.qmd
    - 13.qmd
    - 14.qmd
    - 15.qmd
    - 16.qmd
    - 17.qmd
    - references.qmd

toc: true
toc-depth: 5
  
bibliography: rethinking_2_brms.bib  # bib.bib
biblio-style: apalike
csl: apa.csl
link-citations: true

format:
  html:
    theme: cosmo
    code-copy: true
    reference-location: margin # or block, section, document # footnotes to the margin, rather than default bottom ("document")
    html-math-method: mathjax

engine: knitr
knitr:
  opts_chunk: 
    R.options:
      width: 130  # https://github.com/quarto-dev/quarto-cli/discussions/3934

editor: source

number-sections: true

comments:
  giscus: 
    repo: ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed

highlight-style: github







